base_url = "https://cysec-iitm.github.io"
title = "CyberSecurity Club IITM"
default_language = "en"
compile_sass = false
minify_html = true
generate_feed = true
output_dir = "docs"

taxonomies = [
  { name = "tags" },
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
favicon = "favicon.ico"
image = ""
list_pages = false
twitter_card = false

header_nav = [
  { name = "/home/", url = "/" },
  { name = "/about/", url = "/about" },
  { name = "/events/", url = "/events"},
  { name = "/resources/", url = "/resources"},
]
